### ISSUE TITLE
Setup Project is no compatible with Visual Studio 2015 Community

### ISSUE THREAD

**Issue by muehan** [MSAdministrator/PhishReporter-Outlook-Add-In#2]
Error Message:
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Setup4, "C:\git\PhishReporter-Outlook-Add-In\Setup4\Setup4.vdproj"

Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - PhishReporter, "C:\git\PhishReporter-Outlook-Add-In\PhishReporter.sln"

Are there other dependence's I need?

**Comment by muehan** [comment]
Does work with Visual Studio 2013

**Comment by MSAdministrator** [comment]
muehan, it does seem to work in VS 2013 and 2015.  The dependencies are included in the README file but I've posted them here as well.

Visual Studio Installer Projects Extension: https://visualstudiogallery.msdn.microsoft.com/9abe329c-9bba-44a1-be59-0fbf6151054d
Visual Studio Office Developer Tools

I believe the error you are receiving is because you are missing the Visual Studio Installer Projects Extension.  You can download this at the link above.  Please let me know if this issue is resolved and  then I will close this issue.

**Comment by muehan** [comment]
Hi MsAdmin

Sorry for not reading everything properly.
And maybe the note that VS2013 works too wouldn't be bad.

The link in the readme and in your answer points to the 2013 version for this extension.
Please add this link for the VS2015 version:
https://visualstudiogallery.msdn.microsoft.com/f1cc3f3e-c300-40a7-8797-c509fb8933b9
then it works great!

Many thanks!
